version: 2
updates:
  - package-ecosystem: bundler
    directory: /docs
    schedule:
      interval: daily
  - package-ecosystem: bundler
    directory: /danger
    schedule:
      interval: daily
  - package-ecosystem: bundler
    directory: /mutils
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
