# frozen_string_literal: true

# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

source "https://rubygems.org"

gem "danger", "~> 9.5"
gem "faraday-retry", "~> 2.4"