pull_request_rules:
  - name: automatic approve for Owner
    conditions:
      - author=niteshpurohit
      - status-success=continuous-integration/travis-ci/pr
    actions:
      review:
        message: 'LGTM'
