inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: "2.7.0"
Naming/FileName:
  Exclude:
    - 'benchmark/benchmark-serializer-json.rb'
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'benchmark/benchmark-serializer-json.rb'