plugins:
  - rubocop-rake
  - rubocop-rspec
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: true
Metrics/MethodLength:
  Max: 20
RSpec/MultipleExpectations:
  Max: 10
RSpec/ExampleLength:
  Max: 15
