# frozen_string_literal: true

# Copyright Codevedas Inc. 2019-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
source 'https://rubygems.org'
# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem 'jekyll', '~> 3.10.0'
gem 'minima', '~> 2.5'
# If you have any plugins, put them here!
group :jekyll_plugins do
  gem 'github-pages', '~> 232'
  gem 'just-the-docs', git: 'https://github.com/niteshpurohit/just-the-docs.git'
  gem 'kramdown'
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem 'tzinfo', '>= 1', '< 3'
  gem 'tzinfo-data'
end

# Performance-booster for watching directories on Windows
gem 'http_parser.rb', '~> 0.6.0', platforms: [:jruby]
gem 'wdm', '~> 0.1', platforms: %i[mingw x64_mingw mswin]
