name: Create Release
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-20.04
    name: Release
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rubocop lib
      - name: Run Test
        run: bundle exec rspec
      - name: Publish
        env:
          RUBYGEMS_AUTH_TOKEN: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install -g @commitlint/cli @commitlint/config-angular @semantic-release/changelog @semantic-release/exec
          npm install -g @semantic-release/git @semantic-release/github semantic-release
          npx semantic-release

