name: Test Master
on:
  push:
    branches: [master]
jobs:
  testing:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby:
          - "3.0"
          - "2.7"
          - "2.6"
        include:
          - ruby: "3.0"
            coverage: "true"
    name: Test with ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rubocop lib
      - name: Run Test
        run: bundle exec rspec
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
