name: Publish Gem
on:
  workflow_dispatch:
    inputs:
      release_password:
        description: "Enter Release Password"
        required: true
        default: ""
jobs:
  release:
    runs-on: ubuntu-20.04
    name: Publish Gem
    steps:
      - name: Set ENV
        run: |
          echo "release password: ${{secrets.RELEASE_PASSWORD}}"
          echo "release_password=${{secrets.RELEASE_PASSWORD}}" >> $GITHUB_ENV
      - name: Checkout
        if: github.event.inputs.release_password == env.release_password
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        if: github.event.inputs.release_password == env.release_password
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: Run Rubocop
        if: github.event.inputs.release_password == env.release_password
        run: bundle exec rubocop lib
      - name: Run Test
        if: github.event.inputs.release_password == env.release_password
        run: bundle exec rspec
      - name: Publish
        if: github.event.inputs.release_password == env.release_password
        env:
          RUBYGEMS_AUTH_TOKEN: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_AUTH_TOKEN}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem

