name: Release

on:
  push:
    tags:
      - "v*" # e.g., v1.0.0

jobs:
  test:
    name: Run RSpec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # If your repo has .ruby-version, this action will respect it.
          bundler-cache: true

      - name: RSpec
        run: bin/rspec

  build-and-publish:
    name: Build & Push to RubyGems
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby
      - uses: rubygems/release-gem@v1
