name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    name: Run RSpec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: RSpec
        run: bin/rspec

  push:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
      id-token: write
    environment: release
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby
      - name: Configure RubyGems Credentials
        uses: rubygems/configure-rubygems-credentials@main
      - name: Release
        run: |
          gem build mutils.gemspec
          gem push mutils-*.gem
