name: Release

on:
  push:
    tags:
      - "v*" # e.g., v1.0.0

jobs:
  test:
    name: Run RSpec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # If your repo has .ruby-version, this action will respect it.
          bundler-cache: true
      - name: RSpec
        run: bin/rspec

  push:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
      id-token: write
    # If you configured a GitHub environment on RubyGems, you must use it here.
    environment: release
    steps:
      # Set up
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby
      # Release
      - uses: rubygems/release-gem@v1
